### ISSUE TITLE
Not loading El Capitan

### ISSUE THREAD

**Issue by AndrewHuddleston** [DuoSRX/BtcTickerOSX#4]
Not seeing anythng when I add it in El Capitan. Just the bitcoin logo, not even a update button.

**Comment by AndrewHuddleston** [comment]
![screen shot 2017-04-04 at 10 43 38 am](https://cloud.githubusercontent.com/assets/22681543/24665631/9a15171e-1923-11e7-9cf4-a50e9e8c3e0b.png)

**Comment by DuoSRX** [comment]
Hello! The widget used Mtgox market API to get the prices but Mtgox doesn't exist anymore.

Another thing is that widgets aren't officially supported anymore by Apple. The tool to build them, Dashcode, hasn't been updated since 2012.
I may take a look in the future but the chances of me fixing it are slim. I'd encourage you to look for maintained alternatives or notification bar widgets instead.
